{{- if .Values.ingressExt.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ingressExt.fullname" . }}
  labels:
    app: {{ include "ingressExt.name" . }}
  {{- with .Values.ingressExt.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingressExt.className }}
  ingressClassName: {{ .Values.ingressExt.className }}
  {{- end }}
  {{- if .Values.ingressExt.tls }}
  tls:
    {{- range .Values.ingressExt.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingressExt.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- $services := (include "ingressExt.services" $ | fromYamlArray) }}
          {{- range $svc := $services }}
          - path: {{ $svc.path }}
            pathType: {{ $svc.pathType }}
            backend:
              service:
                name: {{ $svc.name }}
                port:
                  number: {{ $svc.port }}
          {{- end }}
    {{- end }}
{{- end }}