apiVersion: v1
kind: Service
metadata:
  name: {{ include "adminer.fullname" . }}-service
  labels:
    app: {{ include "adminer.name" . }}
  namespace: {{ .Values.namespace.api.name }}
spec:
  ports:
    - port: {{ .Values.adminer.ports.port }}
      targetPort: {{ .Values.adminer.ports.targetPort }}
      protocol: {{ .Values.adminer.ports.protocol }}
      name: {{ .Values.adminer.ports.name }}
  selector:
    app: {{ include "adminer.name" . }}