# Configurações do Spring
spring:
  # Configuração do JPA para desenvolvimento
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
          format_sql: true
  config:
    import: optional:file:.env[.properties]

  # Liquibase
  liquibase:
    contexts: local,test,prod

  # Cache
  cache:
    type: simple

# Logging
logging:
  level:
    root: INFO
    org.springframework: INFO
    com.soat.fiap.food.core.api: DEBUG
    com.soat.fiap.food.core.api.product: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: INFO
    org.springdoc: DEBUG

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
