apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "api.fullname" . }}-config
  labels:
    app: {{ include "api.name" . }}
  namespace: {{ .Values.namespace.api.name }}
data:
  SERVER_CONTEXT_PATH: {{ .Values.api.ingress.path | quote }}
  SERVER_ADDRESS: {{ .Values.api.server.address | quote }}
  SERVER_PORT: {{ .Values.api.server.port | quote }}
  SPRING_PROFILES_ACTIVE: {{ .Values.api.server.profilesActive | quote }}
  MERCADO_PAGO_BASE_URL: {{ .Values.api.mercadoPago.baseUrl | quote }}
  MERCADO_PAGO_NOTIFICATION_URL: {{ .Values.api.mercadoPago.notificationUrl | quote }}
  ZIPKIN_URL: http://{{ include "zipkin.fullname" . }}-service.{{ .Values.namespace.monitor.name }}.svc.cluster.local:{{ .Values.zipkin.ports.port }}
