apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api.fullname" . }}-deployment
  labels:
    app: {{ include "api.name" . }}
  namespace: {{ .Values.namespace.api.name }}
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "api.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "api.name" . }}
    spec:
      containers:
        - name: {{ include "api.name" . }}
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          ports:
            - containerPort: {{ .Values.api.ports.port }}
              name: {{ .Values.api.ports.name }}

          startupProbe:
            httpGet:
              path: {{ .Values.api.ingress.path }}/actuator/health
              port: {{ .Values.api.ports.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30

          livenessProbe:
            httpGet:
              path: {{ .Values.api.ingress.path }}/actuator/health/liveness
              port: {{ .Values.api.ports.port }}
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: {{ .Values.api.ingress.path }}/actuator/health/readiness
              port: {{ .Values.api.ports.port }}
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          env:
            # CONFIGMAP
            - name: SERVER_CONTEXT_PATH
              valueFrom:
                configMapKeyRef:
                  name: {{ include "api.fullname" . }}-config
                  key: SERVER_CONTEXT_PATH
            - name: SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: {{ include "api.fullname" . }}-config
                  key: SERVER_ADDRESS
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "api.fullname" . }}-config
                  key: SERVER_PORT
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "api.fullname" . }}-config
                  key: SPRING_PROFILES_ACTIVE
            - name: MERCADO_PAGO_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "api.fullname" . }}-config
                  key: MERCADO_PAGO_BASE_URL
            - name: MERCADO_PAGO_NOTIFICATION_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "api.fullname" . }}-config
                  key: MERCADO_PAGO_NOTIFICATION_URL
            - name: ZIPKIN_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "api.fullname" . }}-config
                  key: ZIPKIN_URL
            # SECRET
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "api.fullname" . }}-secrets
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "api.fullname" . }}-secrets
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "api.fullname" . }}-secrets
                  key: SPRING_DATASOURCE_PASSWORD
            - name: AZURE_STORAGE_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: {{ include "api.fullname" . }}-secrets
                  key: AZURE_STORAGE_CONNECTION_STRING
            - name: AZURE_STORAGE_CONTAINER_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "api.fullname" . }}-secrets
                  key: AZURE_STORAGE_CONTAINER_NAME
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "api.fullname" . }}-secrets
                  key: JWT_SECRET
            - name: JWT_EXPIRATION_TIME
              valueFrom:
                secretKeyRef:
                  name: {{ include "api.fullname" . }}-secrets
                  key: JWT_EXPIRATION_TIME
            - name: MERCADO_PAGO_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "api.fullname" . }}-secrets
                  key: MERCADO_PAGO_TOKEN
            - name: MERCADO_PAGO_USER_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "api.fullname" . }}-secrets
                  key: MERCADO_PAGO_USER_ID
            - name: MERCADO_PAGO_POS_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "api.fullname" . }}-secrets
                  key: MERCADO_PAGO_POS_ID
          resources:
            limits:
              cpu: {{ .Values.api.resources.limits.cpu }}
              memory: {{ .Values.api.resources.limits.memory }}
            requests:
              cpu: {{ .Values.api.resources.requests.cpu }}
              memory: {{ .Values.api.resources.requests.memory }}
