apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana.fullname" . }}-config
  labels:
    app: {{ include "grafana.name" . }}
  namespace: {{ .Values.namespace.monitor.name }}
data:
  grafana.ini: |
    [server]
    # URL raiz para servir o Grafana
    root_url = %(protocol)s://%(domain)s:%(http_port)s{{ .Values.grafana.ingress.path }}
    # Serve Grafana a partir de um subpath
    serve_from_sub_path = true
  provider.yaml: |
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        updateIntervalSeconds: 10
        options:
          path: {{ .Values.grafana.volumes.grafanadashboards.mountPath }}