name: CI Pipeline

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

permissions:
  id-token: write
  contents: read
  actions: read

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TF_VAR_subscription_id: ${{secrets.AZURE_SUBSCRIPTION_ID}}
  TF_VAR_foodcore-backend-resource-group: ${{secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME}}
  TF_VAR_foodcore-backend-storage-account: ${{secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME}}
  TF_VAR_foodcore-backend-container: ${{secrets.BACKEND_AZURE_STORAGE_ACCOUNT_CONTAINER_NAME}}
  TF_VAR_foodcore-backend-infra-key: ${{secrets.FOODCORE_INFRA_BACKEND_AZURE_KEY}}
  TF_VAR_foodcore-backend-db-key: ${{secrets.FOODCORE_DB_BACKEND_AZURE_KEY}}
  TF_VAR_foodcore-backend-auth-key: ${{secrets.FOODCORE_AUTH_BACKEND_AZURE_KEY}}
  TF_VAR_chart_name: "foodcoreapi"
  TF_VAR_chart_version: "0.1.${{ github.run_number }}"
  TF_VAR_docker_image_tag: "${{ github.run_number }}"
  TF_VAR_jwt_secret: ${{ secrets.FOODCORE_API_JWT_SECRET }}
  TF_VAR_swagger_path: "../build/openapi/swagger.json"
  TF_VAR_mercadopago_base_url: ${{ secrets.FOODCORE_API_MP_BASE_URL }}
  TF_VAR_mercadopago_token: ${{ secrets.FOODCORE_API_MP_TOKEN }}
  TF_VAR_mercadopago_user_id: ${{ secrets.FOODCORE_API_MP_USER_ID }}
  TF_VAR_mercadopago_pos_id: ${{ secrets.FOODCORE_API_MP_POS_ID }}
  TF_VAR_api_ingress_path: "/api"

jobs:
  infra-info:
    runs-on: ubuntu-latest
    env:
      TF_VAR_docker_image_uri: "default"
    outputs:
      acr_login_server: ${{ steps.acr.outputs.acr_login_server }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        working-directory: terraform
        run: |
          terraform init \
            -backend-config="resource_group_name=${{secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME}}" \
            -backend-config="storage_account_name=${{secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME}}" \
            -backend-config="container_name=${{secrets.BACKEND_AZURE_STORAGE_ACCOUNT_CONTAINER_NAME}}" \
            -backend-config="key=${{secrets.BACKEND_AZURE_KEY}}"

      # Somente para que o output seja criado
      - name: Terraform Apply Refresh Only
        working-directory: terraform
        run: terraform apply --refresh-only --auto-approve

      - name: Get ACR Login Server from remote state
        id: acr
        working-directory: terraform
        run: echo "acr_login_server=$(terraform output -raw acr_login_server_from_remote)" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: infra-info
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
          cache: gradle

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Execute Spotless Apply
        run: ./gradlew spotlessApply

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Test with Gradle
        run: ./gradlew test jacocoTestReport

      - name: Build and analyze with SonarCloud
        run: |
          ./gradlew sonar \
            -Dsonar.projectKey="$SONAR_CLOUD_PROJ_KEY" \
            -Dsonar.organization="$SONAR_CLOUD_ORG_KEY" \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token="$SONAR_CLOUD_TOKEN" \
            -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml \
            -Dsonar.qualitygate.wait=true
        env:
          SONAR_CLOUD_ORG_KEY: ${{ secrets.SONAR_CLOUD_ORG_KEY }}
          SONAR_CLOUD_PROJ_KEY: ${{ secrets.SONAR_CLOUD_PROJ_KEY }}
          SONAR_CLOUD_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}

      - name: Generate OpenApi File
        run: |
          ./gradlew generateOpenAPI
        env:
          SERVER_CONTEXT_PATH: "/api"

      - name: Upload OpenApi File
        uses: actions/upload-artifact@v4
        with:
          name: openapi
          path: build/openapi/swagger.json

  push:
    needs: [build, infra-info]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Docker Login to ACR
        run: |
          az acr login --name ${{ needs.infra-info.outputs.acr_login_server }}

      - name: Helm Login to ACR
        run: |
          ACR_LOGIN_SERVER=${{ needs.infra-info.outputs.acr_login_server }}
          ACR_USERNAME=$(az acr credential show --name ${ACR_LOGIN_SERVER} --query "username" -o tsv)
          ACR_PASSWORD=$(az acr credential show --name ${ACR_LOGIN_SERVER} --query "passwords[0].value" -o tsv)
          echo $ACR_PASSWORD | helm registry login $ACR_LOGIN_SERVER --username $ACR_USERNAME --password-stdin

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=${{ needs.infra-info.outputs.acr_login_server }}/foodcoreapi:${{ github.run_number }}
          docker build -t $IMAGE_NAME -f docker/Dockerfile .
          docker push $IMAGE_NAME

      - name: Build and Push Package Helm Chart
        run: |
          CHART_VERSION="0.1.${{ github.run_number }}"
          sed -i "s/^version:.*/version: $CHART_VERSION/" kubernetes/foodcoreapi/Chart.yaml
          sed -i "s/^appVersion:.*/appVersion: $CHART_VERSION/" kubernetes/foodcoreapi/Chart.yaml
          helm dependency update kubernetes/foodcoreapi
          helm package kubernetes/foodcoreapi -d ./charts
          ACR_NAME=${{ needs.infra-info.outputs.acr_login_server }}
          helm push ./charts/foodcoreapi-*.tgz oci://$ACR_NAME/helm

  terraform:
    runs-on: ubuntu-latest
    needs: [push, infra-info]
    env:
      TF_VAR_docker_image_uri: "${{ needs.infra-info.outputs.acr_login_server }}/foodcoreapi"

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Download artifacts - OpenApi File
        uses: actions/download-artifact@v4
        with:
          name: openapi
          path: build/openapi

      - name: Terraform Fmt
        id: fmt
        run: terraform fmt

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="resource_group_name=${{secrets.BACKEND_AZURE_RESOURCE_GROUP_NAME}}" \
            -backend-config="storage_account_name=${{secrets.BACKEND_AZURE_STORAGE_ACCOUNT_NAME}}" \
            -backend-config="container_name=${{secrets.BACKEND_AZURE_STORAGE_ACCOUNT_CONTAINER_NAME}}" \
            -backend-config="key=${{secrets.BACKEND_AZURE_KEY}}"

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: terraform/tfplan
